apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-etcd-data
  namespace: rag-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # storageClassName: standard  # set per cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-minio-data
  namespace: rag-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-data
  namespace: rag-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: standard  # set per cluster
