apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: open-webui-granite
  namespace: rag-demo
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  to:
    kind: Service
    name: open-webui-granite
    weight: 100
  port:
    targetPort: https
  tls:
    termination: edge
  wildcardPolicy: None
