apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rag-demo
resources:
  - namespace.yaml
  - milvus/
commonLabels:
  app.kubernetes.io/part-of: rag-demo
  rag-demo.gitops/sync-wave: "2"
