apiVersion: v1
kind: Namespace
metadata:
  name: rag-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/part-of: rag-demo
    openshift.io/cluster-monitoring: "true"
