apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
  annotations:
    openshift.io/display-name: "Red Hat OpenShift AI"
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: rag-demo
    openshift.io/cluster-monitoring: "true"
